/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graficaciongrupo1;

import com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import com.badlogic.gdx.graphics.Color;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.google.common.primitives.Floats;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author libookami
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    PanelCanvas canvas1;
    
    Figura figuraSelecionada =  null;
    Punto puntoSelecionado = null;
    
    Figura3D figura3DSelecionada = null;
    
    Preferences prefs;
    
    File ultimo_archivo_usado;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        prefs = Preferences.systemNodeForPackage(this.getClass());
        
        ultimo_archivo_usado = new File(prefs.get("ULTIMA_RUTA_USADA", ""));
        
        System.out.println("Inicializado correctamente");
        
        LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
        config.title = "PracticaGraficacion";
        config.width = 1280;
        config.height = 720;
        config.vSyncEnabled = true;
        config.foregroundFPS = 60;
        
        canvas1 = new PanelCanvas(this);
        
         //Inicializar los canvas.
        LwjglAWTCanvas panelcanvas = new LwjglAWTCanvas(canvas1, config);
        //Agregar el canvas de dibujado.
        PNLDibujo.add(panelcanvas.getCanvas());
        jList1.setModel(canvas1.listaFiguras);
        
        jList1.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                figuraSelecionada = jList1.getSelectedValue();
                if(figuraSelecionada != null){
                    jTextField1.setText(figuraSelecionada.getNombre());
                    jList2.setModel(figuraSelecionada.getPuntos());
                }
                else
                    jTextField1.setText("");
            }
            
        });
        
        jList2.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                puntoSelecionado = jList2.getSelectedValue();
                
                if(puntoSelecionado != null){
                    jTextField2.setText("" + puntoSelecionado.getpX());
                    jTextField3.setText("" + puntoSelecionado.getpY());
                }
            }
        });
        
        jLFiguras3D.setModel(canvas1.listaFiguras3D);
        jLFiguras3D.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                figura3DSelecionada = jLFiguras3D.getSelectedValue();
                if(figura3DSelecionada != null){
                    JtfNombre.setText(figura3DSelecionada.getNombre());
                    Jtf3Dsx.setText(""+figura3DSelecionada.getSx());
                    Jtf3Dsy.setText(""+figura3DSelecionada.getSy());
                    Jtf3Dsz.setText(""+figura3DSelecionada.getSz());
                    Color c1 = figura3DSelecionada.getColor();
                    java.awt.Color color4 = new java.awt.Color(c1.r,c1.g,c1.b,c1.a);
                    BtnColor.setBackground(color4);
                    JcbTipos.setSelectedItem(figura3DSelecionada.getTipo());
                }
                else {
                    JtfNombre.setText("");
                    Jtf3Dsx.setText("" + 0);
                    Jtf3Dsy.setText("" + 0);
                    Jtf3Dsz.setText("" + 0);
                }
            }
        });
        
        DefaultComboBoxModel<Figura3D.TiposFigura3D> combo_model = new DefaultComboBoxModel<>();
        JcbTipos.setModel(combo_model);
        for (Figura3D.TiposFigura3D t : Figura3D.TiposFigura3D.values())
            combo_model.addElement(t);
        
        Cargar(ultimo_archivo_usado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel14 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        tabEscalado = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JtfSx = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JtfSy = new javax.swing.JTextField();
        BtnEscalado = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        JtfAngulo = new javax.swing.JTextField();
        BtnAngulo = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        JtfShx = new javax.swing.JTextField();
        JtfShy = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BtnShx = new javax.swing.JButton();
        BtnShy = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JtfTx = new javax.swing.JTextField();
        JtfTy = new javax.swing.JTextField();
        BtnTraslacion = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        BtnCamArriba = new javax.swing.JButton();
        BtnCamIzquierda = new javax.swing.JButton();
        BtnCamAbajo = new javax.swing.JButton();
        BtnCamDerecha = new javax.swing.JButton();
        BtnCamFrente = new javax.swing.JButton();
        BtnCamAtras = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel19 = new javax.swing.JPanel();
        JtfNombre = new javax.swing.JTextField();
        Jtf3Dsx = new javax.swing.JTextField();
        Jtf3Dsz = new javax.swing.JTextField();
        Jtf3Dsy = new javax.swing.JTextField();
        JcbTipos = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        BtnColor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLFiguras3D = new javax.swing.JList<>();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        radio2D = new javax.swing.JRadioButton();
        radio3D = new javax.swing.JRadioButton();
        PNLDibujo = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(20, 35));

        jLabel4.setText("Escala:");

        jTextField4.setText("20");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton7.setText("Aplicar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        jPanel11.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane2.setPreferredSize(new java.awt.Dimension(541, 350));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Figuras"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jList1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Nombre:");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.setMinimumSize(new java.awt.Dimension(72, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jSplitPane2.setLeftComponent(jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Puntos"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(jList2);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel2.setText("pX:");

        jLabel3.setText("Py:");

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Editar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jSplitPane2.setRightComponent(jPanel2);

        jPanel12.add(jSplitPane2);

        jPanel11.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel7.setPreferredSize(new java.awt.Dimension(600, 300));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setText("Sx:");

        JtfSx.setText("0");
        JtfSx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfSxActionPerformed(evt);
            }
        });

        jLabel8.setText("Sy:");

        JtfSy.setText("0");

        BtnEscalado.setText("Aplicar");
        BtnEscalado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEscaladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnEscalado)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JtfSx, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JtfSy, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JtfSx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JtfSy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnEscalado)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        tabEscalado.addTab("Escalado", jPanel8);

        jLabel9.setText("Angulo:");

        JtfAngulo.setText("0");
        JtfAngulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfAnguloActionPerformed(evt);
            }
        });

        BtnAngulo.setText("Aplicar");
        BtnAngulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAngulo)
                    .addComponent(JtfAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(475, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(JtfAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAngulo)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        tabEscalado.addTab("Rotacion ", jPanel9);

        jLabel10.setText("Shx:");

        JtfShx.setText("0");
        JtfShx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfShxActionPerformed(evt);
            }
        });

        JtfShy.setText("0");

        jLabel11.setText("Shy:");

        BtnShx.setText("Aplicar");
        BtnShx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnShxActionPerformed(evt);
            }
        });

        BtnShy.setText("Aplicar");
        BtnShy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnShyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JtfShx, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnShx))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JtfShy, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnShy)))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(JtfShx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnShx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JtfShy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnShy))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        tabEscalado.addTab("Sesgado", jPanel10);

        jLabel5.setText("Tx:");

        jLabel6.setText("Ty:");

        JtfTx.setText("0");
        JtfTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfTxActionPerformed(evt);
            }
        });

        JtfTy.setText("0");

        BtnTraslacion.setText("Aplicar");
        BtnTraslacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTraslacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnTraslacion)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JtfTx, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JtfTy, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JtfTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JtfTy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnTraslacion)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        tabEscalado.addTab("Traslacion", jPanel6);

        jPanel7.add(tabEscalado);

        jPanel11.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Figuras", jPanel11);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Camara"));

        BtnCamArriba.setText("^");
        BtnCamArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCamArribaActionPerformed(evt);
            }
        });

        BtnCamIzquierda.setText("<");
        BtnCamIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCamIzquierdaActionPerformed(evt);
            }
        });

        BtnCamAbajo.setText("v");
        BtnCamAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCamAbajoActionPerformed(evt);
            }
        });

        BtnCamDerecha.setText(">");
        BtnCamDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCamDerechaActionPerformed(evt);
            }
        });

        BtnCamFrente.setText("Frente");

        BtnCamAtras.setText("Atras");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCamIzquierda)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCamAbajo)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(BtnCamArriba)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnCamDerecha)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnCamAtras)
                                    .addComponent(BtnCamFrente))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCamArriba)
                    .addComponent(BtnCamFrente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCamIzquierda)
                    .addComponent(BtnCamDerecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCamAbajo)
                    .addComponent(BtnCamAtras))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Figuras 3D"));
        jPanel18.setLayout(new java.awt.GridLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jButton8.setText("Agregar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel12.setText("Nombre");

        jLabel13.setText("SX:");

        jLabel14.setText("SY");

        jLabel15.setText("SZ");

        jLabel16.setText("Tipo");

        jButton15.setText("Eliminar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel17.setText("Color");

        BtnColor.setText("Color");
        BtnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jtf3Dsz, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtf3Dsx, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtf3Dsy, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnColor)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jButton15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addComponent(JcbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 367, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(JtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Jtf3Dsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Jtf3Dsy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Jtf3Dsz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(BtnColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JcbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton15)))
        );

        jSplitPane1.setBottomComponent(jPanel19);

        jScrollPane3.setViewportView(jLFiguras3D);

        jSplitPane1.setLeftComponent(jScrollPane3);

        jPanel18.add(jSplitPane1);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("3D", jPanel16);

        jPanel14.add(jTabbedPane1);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel15.setPreferredSize(new java.awt.Dimension(200, 35));

        buttonGroup1.add(radio2D);
        radio2D.setSelected(true);
        radio2D.setText("2D");
        radio2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio2DActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio3D);
        radio3D.setText("3D");
        radio3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio3DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(radio2D)
                .addGap(18, 18, 18)
                .addComponent(radio3D)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio2D)
                    .addComponent(radio3D))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel13.add(jPanel15, java.awt.BorderLayout.PAGE_START);

        PNLDibujo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PNLDibujo.setMinimumSize(new java.awt.Dimension(6, 6));
        PNLDibujo.setName(""); // NOI18N
        PNLDibujo.setPreferredSize(new java.awt.Dimension(600, 800));
        PNLDibujo.setVerifyInputWhenFocusTarget(false);
        PNLDibujo.setLayout(new java.awt.BorderLayout());
        jPanel13.add(PNLDibujo, java.awt.BorderLayout.PAGE_END);

        jPanel14.add(jPanel13);

        getContentPane().add(jPanel14, java.awt.BorderLayout.CENTER);

        jMenu3.setText("Archivo");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Cargar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Ayuda");

        jMenuItem1.setText("Acerca de");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
                "Nombres:\nContreras Najera Gael\nOrtega Castro Karla Valeria\nSanchez Corona Denis\nSanvicente Alvarez Alexis Rodrigo\nMateria Graficacion",
        "Acerca de",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooser jfc = new JFileChooser(ultimo_archivo_usado);
        
        if(jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
            Guardar(jfc.getSelectedFile());
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void Guardar(File archivo){
         String datos = "";
        
        for (int i = 0; i < canvas1.listaFiguras.size(); i++) {
            datos += canvas1.listaFiguras.get(i).serialiar();
            datos += "\n";
        }
        
        System.out.println(datos);
        
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(archivo));
            bw.append(datos);
            bw.close();
            
            prefs.put("ULTIMA_RUTA_USADA", archivo.getPath());
            ultimo_archivo_usado = archivo;
        } catch (IOException ex) {
            System.err.println(ex.getMessage());
        }
    }
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       JFileChooser jfc = new JFileChooser(prefs.get("ULTIMA_RUTA_USADA", ""));
        
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            Cargar(jfc.getSelectedFile());
        } 
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public void Cargar(File f){
        try {
            canvas1.listaFiguras.clear();
            
            BufferedReader br = new BufferedReader(new FileReader(f));
            String linea;
            
            while((linea = br.readLine()) != null){
                System.out.println("Linea: " + linea);
                String[] tokens = linea.split(",");
                
                Figura fig = new Figura(tokens[0]);
                
                for (int i = 1; i < tokens.length; i+=2) {
                    if((i+1) < tokens.length){
                        float px = Floats.tryParse(tokens[i]);
                        float py = Floats.tryParse(tokens[i+1]);

                        Punto p = new Punto(px, py);
                        fig.getPuntos().addElement(p);
                    }
                }
                canvas1.listaFiguras.addElement(fig);
                
                prefs.put("ULTIMA_RUTA_USADA", f.getPath());
                ultimo_archivo_usado = f;
                
                jList1.updateUI();
                jList2.updateUI();
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error al cargar.",JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(!jTextField4.getText().isEmpty()){
            Figura.escala = Integer.parseInt(jTextField4.getText());
        } else{
            JOptionPane.showMessageDialog(null, "Ingresa una ecala validad");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void BtnTraslacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTraslacionActionPerformed
        if(figuraSelecionada != null){
            float tx = Floats.tryParse(JtfTx.getText());
            float ty = Floats.tryParse(JtfTy.getText());

            Matriz33 m = Operaciones2D.getMatrizTraslacion(tx, ty);

            System.out.println(m);

            figuraSelecionada.Tranformar(m);
            jList2.updateUI();
        }else {
            JOptionPane.showMessageDialog(null, "Necesitas selecionar una figura");
        }
    }//GEN-LAST:event_BtnTraslacionActionPerformed

    private void JtfTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfTxActionPerformed

    private void BtnShyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnShyActionPerformed
        if(figuraSelecionada != null){
            float shy = Floats.tryParse(JtfShy.getText());

            Matriz33 m = Operaciones2D.getMatrizSesgadoY(shy);

            //System.out.println(m);

            figuraSelecionada.Tranformar(m);
            jList2.updateUI();
        }else {
            JOptionPane.showMessageDialog(null, "Necesitas selecionar una figura");
        }
    }//GEN-LAST:event_BtnShyActionPerformed

    private void BtnShxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnShxActionPerformed
        if(figuraSelecionada != null){
            float shx = Floats.tryParse(JtfShx.getText());

            Matriz33 m = Operaciones2D.getMatrizSesgadoX(shx);

            //System.out.println(m);

            figuraSelecionada.Tranformar(m);
            jList2.updateUI();
        }else {
            JOptionPane.showMessageDialog(null, "Necesitas selecionar una figura");
        }
    }//GEN-LAST:event_BtnShxActionPerformed

    private void JtfShxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfShxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfShxActionPerformed

    private void BtnAnguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnguloActionPerformed
        if(figuraSelecionada != null){
            float angulo = Floats.tryParse(JtfAngulo.getText());

            Matriz33 m = Operaciones2D.getMatrizRotacion(angulo);

            System.out.println(m);

            figuraSelecionada.Tranformar(m);
            jList2.updateUI();
        }else {
            JOptionPane.showMessageDialog(null, "Necesitas selecionar una figura");
        }
    }//GEN-LAST:event_BtnAnguloActionPerformed

    private void JtfAnguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfAnguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfAnguloActionPerformed

    private void BtnEscaladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEscaladoActionPerformed
        if(figuraSelecionada != null){
            float sx = Floats.tryParse(JtfSx.getText());
            float sy = Floats.tryParse(JtfSy.getText());

            Matriz33 m = Operaciones2D.getMatrizEscalado(sx, sy);

            //System.out.println(m);

            figuraSelecionada.Tranformar(m);
            jList2.updateUI();
        }else {
            JOptionPane.showMessageDialog(null, "Necesitas selecionar una figura");
        }
    }//GEN-LAST:event_BtnEscaladoActionPerformed

    private void JtfSxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfSxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfSxActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(puntoSelecionado != null){
            figuraSelecionada.getPuntos().removeElement(puntoSelecionado);
            jList2.updateUI();
            jTextField2.setText("");
            jTextField3.setText("");

        }else {
            JOptionPane.showMessageDialog(null, "Necesitas selecionar los puntos a eliminar");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(puntoSelecionado != null){
            float px = Floats.tryParse(jTextField2.getText());
            float py = Floats.tryParse(jTextField3.getText());

            puntoSelecionado.setpX(px);
            puntoSelecionado.setpY(py);
            jList2.updateUI();

            jTextField2.setText("");
            jTextField3.setText("");
        }else {
            JOptionPane.showMessageDialog(null, "Necesitas selecionar los puntos a editar");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(figuraSelecionada != null){
            if(jTextField2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Campo px requerido");
            }else if(jTextField3.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Campo py requerido");
            }else {
                float px = Floats.tryParse(jTextField2.getText());
                float py = Floats.tryParse(jTextField3.getText());
                Punto p = new Punto(px, py);

                figuraSelecionada.getPuntos().addElement(p);

                jTextField2.setText("");
                jTextField3.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Necesitas selecionar una figura");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(figuraSelecionada != null){
            canvas1.listaFiguras.removeElement(figuraSelecionada);
            jList1.updateUI();
        }else {
            JOptionPane.showMessageDialog(null, "Necesitas selecionar una figura");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(figuraSelecionada != null){
            if(!jTextField1.getText().isEmpty()){
                figuraSelecionada.setNombre(jTextField1.getText());
                jList1.updateUI();
                jTextField1.setText("");
            }
        }else {
            JOptionPane.showMessageDialog(null, "Necesitas selecionar una figura");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!jTextField1.getText().isEmpty()){
            Figura f = new Figura(jTextField1.getText());
            canvas1.listaFiguras.addElement(f);
            jTextField1.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Campo nombre requerido");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void radio3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio3DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio3DActionPerformed

    private void radio2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio2DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio2DActionPerformed

    private void BtnCamArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCamArribaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCamArribaActionPerformed

    private void BtnCamIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCamIzquierdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCamIzquierdaActionPerformed

    private void BtnCamAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCamAbajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCamAbajoActionPerformed

    private void BtnCamDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCamDerechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCamDerechaActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if(figura3DSelecionada != null){
            canvas1.listaFiguras3D.removeElement(figura3DSelecionada);
            jLFiguras3D.updateUI();
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String nombre = JtfNombre.getText();
        float sx = Floats.tryParse(Jtf3Dsx.getText());
        float sy = Floats.tryParse(Jtf3Dsy.getText());
        float sz = Floats.tryParse(Jtf3Dsz.getText());
        Figura3D.TiposFigura3D tipo = (Figura3D.TiposFigura3D)JcbTipos.getSelectedItem();
        java.awt.Color c1 = BtnColor.getBackground();
        Color color = new Color(c1.getRed(), c1.getBlue(), c1.getGreen(), c1.getAlpha());
        
        Figura3D nuevo = new Figura3D(nombre, sx, sy, sz, color, tipo);
        
        canvas1.listaFiguras3D.addElement(nuevo);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void BtnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnColorActionPerformed
        JColorChooser Jcc = new JColorChooser();
        if (JOptionPane.showConfirmDialog(this, Jcc,"Seleciona un color",JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE) == 0){
            java.awt.Color color = Jcc.getColor();
            BtnColor.setBackground(color);
        }
    }//GEN-LAST:event_BtnColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
            javax.swing.UIManager.setLookAndFeel(new FlatDarculaLaf());
        }catch(Exception ex){
            System.out.println("Fallo al instalar el Theme");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAngulo;
    public javax.swing.JButton BtnCamAbajo;
    public javax.swing.JButton BtnCamArriba;
    public javax.swing.JButton BtnCamAtras;
    public javax.swing.JButton BtnCamDerecha;
    public javax.swing.JButton BtnCamFrente;
    public javax.swing.JButton BtnCamIzquierda;
    private javax.swing.JButton BtnColor;
    private javax.swing.JButton BtnEscalado;
    private javax.swing.JButton BtnShx;
    private javax.swing.JButton BtnShy;
    private javax.swing.JButton BtnTraslacion;
    private javax.swing.JComboBox<Figura3D.TiposFigura3D> JcbTipos;
    private javax.swing.JTextField Jtf3Dsx;
    private javax.swing.JTextField Jtf3Dsy;
    private javax.swing.JTextField Jtf3Dsz;
    private javax.swing.JTextField JtfAngulo;
    private javax.swing.JTextField JtfNombre;
    private javax.swing.JTextField JtfShx;
    private javax.swing.JTextField JtfShy;
    private javax.swing.JTextField JtfSx;
    private javax.swing.JTextField JtfSy;
    private javax.swing.JTextField JtfTx;
    private javax.swing.JTextField JtfTy;
    public javax.swing.JPanel PNLDibujo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JList<Figura3D> jLFiguras3D;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<Figura> jList1;
    private javax.swing.JList<Punto> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    public javax.swing.JRadioButton radio2D;
    public javax.swing.JRadioButton radio3D;
    private javax.swing.JTabbedPane tabEscalado;
    // End of variables declaration//GEN-END:variables
}
